# Generated by Django 5.2.8 on 2025-12-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_order_city_order_full_name_order_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_department',
            field=models.CharField(blank=True, help_text='Відділення Нової Пошти / Укрпошти', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('nova_poshta', 'Нова Пошта'), ('ukr_poshta', 'Укрпошта'), ('courier', 'Кур’єр')], default='nova_poshta', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Оплата карткою'), ('cod', 'Накладений платіж'), ('bank', 'Банківський переказ')], default='card', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
